package com.epro.framework.model;

// Generated 13 Oct, 2012 11:47:06 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Clients generated by hbm2java
 */
public class Clients implements java.io.Serializable {

	private long clientId;
	private String clientName;
	private String description;
	private String businessType;
	private String address;
	private String city;
	private String state;
	private String zip;
	private String country;
 	private boolean status;
	private String contactPerson;
	private String workPhone;	
	private String faxNo;
	private String mobileNumber;
	private String emailId;	
 	private Date modifiedDate;
 	private boolean isDeleted;
 	private String logoPath;
  	
	
	public Clients() {
	}

	public Clients(long clientId,String clientName,String businessType,String address,String city,String state,
				String zip,String country,boolean status,String contactPerson,String workPhone,
				String mobileNumber,String emailId,Date modifiedDate,String imagePath) {
		this.clientId = clientId;
		this.clientName = clientName;
		this.businessType = businessType;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.country = country;
  		this.status = status;
		this.contactPerson = contactPerson;
		this.workPhone = workPhone;
		this.mobileNumber = mobileNumber;
		this.emailId = emailId;
 		this.modifiedDate = modifiedDate;
 	}
	
	public Clients(long clientId,String clientName,String businessType,String address,String city,String state,
			String zip,String country,boolean status,String contactPerson,String workPhone,
			String mobileNumber, String emailId, Date modifiedDate, String imagePath, boolean isDeleted,
			String logoPath) {
		this.clientId = clientId;
		this.clientName = clientName;
		this.businessType = businessType;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.country = country;
		this.status = status;
		this.contactPerson = contactPerson;
		this.workPhone = workPhone;
		this.mobileNumber = mobileNumber;
		this.emailId = emailId;
		this.modifiedDate = modifiedDate;
		this.isDeleted = isDeleted;
		this.logoPath = logoPath;

	}

	public long getClientId() {
		return clientId;
	}

	public void setClientId(long clientId) {
		this.clientId = clientId;
	}

	public String getClientName() {
		return clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getBusinessType() {
		return businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public boolean getStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public String getContactPerson() {
		return contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getWorkPhone() {
		return workPhone;
	}

	public void setWorkPhone(String workPhone) {
		this.workPhone = workPhone;
	}

	public String getFaxNo() {
		return faxNo;
	}

	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}

	public String getMobileNumber() {
		return mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public String getLogoPath() {
		return logoPath;
	}

	public void setLogoPath(String logoPath) {
		this.logoPath = logoPath;
	}
 

	 

	 

}
