package com.epro.framework.model;

// Generated Oct 19, 2012 1:09:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * Menus generated by hbm2java
 */
public class Menus implements java.io.Serializable {

	private long menuId;
	private String menuName;
	private String menuDescription;
	private Date modifiedDate;
	private int orderId;
	private Set<SubMenus> subMenuses;

	public Menus() {

	}

	public Menus(long menuId, String menuName, Date modifiedDate, int orderId) {
		this.menuId = menuId;
		this.menuName = menuName;
		this.modifiedDate = modifiedDate;
		this.orderId = orderId;
	}

	public Menus(long menuId, String menuName, String menuDescription, Date modifiedDate, int orderId) {
		this.menuId = menuId;
		this.menuName = menuName;
		this.menuDescription = menuDescription;
		this.modifiedDate = modifiedDate;
		this.orderId = orderId;
	}

	public long getMenuId() {
		return menuId;
	}

	public void setMenuId(long menuId) {
		this.menuId = menuId;
	}

	public String getMenuName() {
		return menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuDescription() {
		return menuDescription;
	}

	public void setMenuDescription(String menuDescription) {
		this.menuDescription = menuDescription;
	}

	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public int getOrderId() {
		return orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public Set<SubMenus> getSubMenuses() {
		return subMenuses;
	}

	public void setSubMenuses(Set<SubMenus> subMenuses) {
		this.subMenuses = subMenuses;
	}
 
}
