package com.epro.framework.model;

// Generated Oct 19, 2012 1:09:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserAccessPermission generated by hbm2java
 */
public class RoleAccessPermission implements java.io.Serializable {

	private long permissionId;	
	private Roles roles;
 	private long menuId;		
	private long subMenuId;	
	private boolean isViewEnabled;
	private boolean isCreateEnabled;
	private boolean isEditEnabled;
	private boolean isDeleteEnabled;
	private Date modifiedDate;
	

	public RoleAccessPermission() {

	}

 	public RoleAccessPermission(long permissionId, int roleId,long menuId,long subMenuId,boolean isViewEnabled,boolean isCreateEnabled,
 			boolean isEditEnabled,boolean isDeleteEnabled,Date modifiedDate) {
		 this.permissionId = permissionId; 
 		 this.menuId = menuId;
		 this.subMenuId = subMenuId;
		 this.isViewEnabled = isViewEnabled;
		 this.isCreateEnabled = isCreateEnabled;
		 this.isEditEnabled = isEditEnabled;
		 this.isDeleteEnabled = isDeleteEnabled;
	}

	public long getPermissionId() {
		return permissionId;
	}

	public void setPermissionId(long permissionId) {
		this.permissionId = permissionId;
	}
 
 	public long getMenuId() {
		return menuId;
	}

	public void setMenuId(long menuId) {
		this.menuId = menuId;
	}

	public long getSubMenuId() {
		return subMenuId;
	}

	public void setSubMenuId(long subMenuId) {
		this.subMenuId = subMenuId;
	}

	public boolean getIsViewEnabled() {
		return isViewEnabled;
	}

	public void setIsViewEnabled(boolean isViewEnabled) {
		this.isViewEnabled = isViewEnabled;
	}

	public boolean getIsCreateEnabled() {
		return isCreateEnabled;
	}

	public void setIsCreateEnabled(boolean isCreateEnabled) {
		this.isCreateEnabled = isCreateEnabled;
	}

	public boolean getIsEditEnabled() {
		return isEditEnabled;
	}

	public void setIsEditEnabled(boolean isEditEnabled) {
		this.isEditEnabled = isEditEnabled;
	}

	public boolean getIsDeleteEnabled() {
		return isDeleteEnabled;
	}

	public void setIsDeleteEnabled(boolean isDeleteEnabled) {
		this.isDeleteEnabled = isDeleteEnabled;
	}

	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public Roles getRoles() {
		return roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	 
}
