package com.epro.framework.model;

// Generated Oct 19, 2012 1:09:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SubMenus generated by hbm2java
 */
public class SubMenus implements java.io.Serializable {

	private long subMenuId;	
	private Menus menus;
 	private String subMenuName;	
	private String subMenuDescription;
	private Date modifiedDate;
	private int orderId;

	public SubMenus() {

	}

	public SubMenus(long subMenuId,Menus menus, String subMenuName, Date modifiedDate, int orderId) {
		this.subMenuId = subMenuId;
		this.menus = menus;
		this.subMenuName = subMenuName;
		this.modifiedDate = modifiedDate;
		this.orderId = orderId;
	}

	public SubMenus(long subMenuId,Menus menus, String subMenuName, String subMenuDescription, Date modifiedDate, int orderId) {
		this.subMenuId = subMenuId;
		this.menus = menus;
		this.subMenuName = subMenuName;
		this.subMenuDescription = subMenuDescription;
		this.modifiedDate = modifiedDate;
		this.orderId = orderId;
	}

	public long getSubMenuId() {
		return subMenuId;
	}

	public void setSubMenuId(long subMenuId) {
		this.subMenuId = subMenuId;
	}
	
	public Menus getMenus() {
		return menus;
	}

	public void setMenus(Menus menus) {
		this.menus = menus;
	}

	public String getSubMenuName() {
		return subMenuName;
	}

	public void setSubMenuName(String subMenuName) {
		this.subMenuName = subMenuName;
	}

	public String getSubMenuDescription() {
		return subMenuDescription;
	}

	public void setSubMenuDescription(String subMenuDescription) {
		this.subMenuDescription = subMenuDescription;
	}

	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public int getOrderId() {
		return orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}
}
